#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using HCP.Fr.SqlCe.DataAccess;


namespace HCP.Fr.SqlCe.DataAccess	
{
	public partial class HCPFrSqlCe : OpenAccessContext, IHCPFrSqlCeUnitOfWork
	{
		private static string connectionStringName = @"HCPFrSqlCeConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("HCPFrSqlCe.rlinq");
	
		public HCPFrSqlCe()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public HCPFrSqlCe(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public HCPFrSqlCe(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public HCPFrSqlCe(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public HCPFrSqlCe(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Scope_info> Scope_infos 
		{
	    	get
	    	{
	        	return this.GetAll<Scope_info>();
	    	}
		}
		
		public IQueryable<Scope_config> Scope_configs 
		{
	    	get
	    	{
	        	return this.GetAll<Scope_config>();
	    	}
		}
		
		public IQueryable<Schema_info> Schema_infos 
		{
	    	get
	    	{
	        	return this.GetAll<Schema_info>();
	    	}
		}
		
		public IQueryable<Patients_tracking> Patients_trackings 
		{
	    	get
	    	{
	        	return this.GetAll<Patients_tracking>();
	    	}
		}
		
		public IQueryable<Patient> Patients 
		{
	    	get
	    	{
	        	return this.GetAll<Patient>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "SqlCe";
			backend.ProviderName = "Microsoft.SqlServerCe.Client.3.5";
			return backend;
		}
	}

	public interface IHCPFrSqlCeUnitOfWork : IUnitOfWork
	{
		IQueryable<Scope_info> Scope_infos 
		{ 
			get;
		}

		IQueryable<Scope_config> Scope_configs 
		{ 
			get;
		}

		IQueryable<Schema_info> Schema_infos 
		{ 
			get;
		}

		IQueryable<Patients_tracking> Patients_trackings 
		{ 
			get;
		}

		IQueryable<Patient> Patients 
		{ 
			get;
		}

	}
}
#pragma warning restore 1591

