#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace HCP.Fr.SqlCe.DataAccess	
{
	public partial class Patient
	{
		private Guid _id;
		public virtual Guid Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private string _ssn_Ou_Identité;
		public virtual string Ssn_ou_identité 
		{ 
		    get
		    {
		        return this._ssn_Ou_Identité;
		    }
		    set
		    {
		        this._ssn_Ou_Identité = value;
		    }
		}
		
		private string _numero_Carte_Identité;
		public virtual string Numero_carte_identité 
		{ 
		    get
		    {
		        return this._numero_Carte_Identité;
		    }
		    set
		    {
		        this._numero_Carte_Identité = value;
		    }
		}
		
		private string _identité_Expiration;
		public virtual string Identité_expiration 
		{ 
		    get
		    {
		        return this._identité_Expiration;
		    }
		    set
		    {
		        this._identité_Expiration = value;
		    }
		}
		
		private string _identité_Date_De_Publication;
		public virtual string Identité_date_de_publication 
		{ 
		    get
		    {
		        return this._identité_Date_De_Publication;
		    }
		    set
		    {
		        this._identité_Date_De_Publication = value;
		    }
		}
		
		private string _adresse_Carte_Identité;
		public virtual string Adresse_carte_identité 
		{ 
		    get
		    {
		        return this._adresse_Carte_Identité;
		    }
		    set
		    {
		        this._adresse_Carte_Identité = value;
		    }
		}
		
		private string _nom;
		public virtual string Nom 
		{ 
		    get
		    {
		        return this._nom;
		    }
		    set
		    {
		        this._nom = value;
		    }
		}
		
		private string _prénom;
		public virtual string Prénom 
		{ 
		    get
		    {
		        return this._prénom;
		    }
		    set
		    {
		        this._prénom = value;
		    }
		}
		
		private string _deuxième_Nom;
		public virtual string Deuxième_nom 
		{ 
		    get
		    {
		        return this._deuxième_Nom;
		    }
		    set
		    {
		        this._deuxième_Nom = value;
		    }
		}
		
		private string _date_Naissance;
		public virtual string Date_naissance 
		{ 
		    get
		    {
		        return this._date_Naissance;
		    }
		    set
		    {
		        this._date_Naissance = value;
		    }
		}
		
		private string _raison_De_La_Visite;
		public virtual string Raison_de_la_visite 
		{ 
		    get
		    {
		        return this._raison_De_La_Visite;
		    }
		    set
		    {
		        this._raison_De_La_Visite = value;
		    }
		}
		
		private string _taille;
		public virtual string Taille 
		{ 
		    get
		    {
		        return this._taille;
		    }
		    set
		    {
		        this._taille = value;
		    }
		}
		
		private string _yeux;
		public virtual string Yeux 
		{ 
		    get
		    {
		        return this._yeux;
		    }
		    set
		    {
		        this._yeux = value;
		    }
		}
		
		private string _cheveux;
		public virtual string Cheveux 
		{ 
		    get
		    {
		        return this._cheveux;
		    }
		    set
		    {
		        this._cheveux = value;
		    }
		}
		
		private string _adresse;
		public virtual string Adresse 
		{ 
		    get
		    {
		        return this._adresse;
		    }
		    set
		    {
		        this._adresse = value;
		    }
		}
		
		private string _appartement;
		public virtual string Appartement 
		{ 
		    get
		    {
		        return this._appartement;
		    }
		    set
		    {
		        this._appartement = value;
		    }
		}
		
		private string _ville;
		public virtual string Ville 
		{ 
		    get
		    {
		        return this._ville;
		    }
		    set
		    {
		        this._ville = value;
		    }
		}
		
		private string _état_Ou_Région;
		public virtual string État_ou_région 
		{ 
		    get
		    {
		        return this._état_Ou_Région;
		    }
		    set
		    {
		        this._état_Ou_Région = value;
		    }
		}
		
		private string _pays;
		public virtual string Pays 
		{ 
		    get
		    {
		        return this._pays;
		    }
		    set
		    {
		        this._pays = value;
		    }
		}
		
		private string _boite_Postale;
		public virtual string Boite_postale 
		{ 
		    get
		    {
		        return this._boite_Postale;
		    }
		    set
		    {
		        this._boite_Postale = value;
		    }
		}
		
		private string _genre;
		public virtual string Genre 
		{ 
		    get
		    {
		        return this._genre;
		    }
		    set
		    {
		        this._genre = value;
		    }
		}
		
		private string _naissance;
		public virtual string Naissance 
		{ 
		    get
		    {
		        return this._naissance;
		    }
		    set
		    {
		        this._naissance = value;
		    }
		}
		
		private string _lieux_Naissance;
		public virtual string Lieux_naissance 
		{ 
		    get
		    {
		        return this._lieux_Naissance;
		    }
		    set
		    {
		        this._lieux_Naissance = value;
		    }
		}
		
		private string _téléphone;
		public virtual string Téléphone 
		{ 
		    get
		    {
		        return this._téléphone;
		    }
		    set
		    {
		        this._téléphone = value;
		    }
		}
		
		private string _fax;
		public virtual string Fax 
		{ 
		    get
		    {
		        return this._fax;
		    }
		    set
		    {
		        this._fax = value;
		    }
		}
		
		private string _email;
		public virtual string Email 
		{ 
		    get
		    {
		        return this._email;
		    }
		    set
		    {
		        this._email = value;
		    }
		}
		
		private string _twitter;
		public virtual string Twitter 
		{ 
		    get
		    {
		        return this._twitter;
		    }
		    set
		    {
		        this._twitter = value;
		    }
		}
		
		private string _whatsapp;
		public virtual string Whatsapp 
		{ 
		    get
		    {
		        return this._whatsapp;
		    }
		    set
		    {
		        this._whatsapp = value;
		    }
		}
		
		private string _linkedin;
		public virtual string Linkedin 
		{ 
		    get
		    {
		        return this._linkedin;
		    }
		    set
		    {
		        this._linkedin = value;
		    }
		}
		
		private string _employeur;
		public virtual string Employeur 
		{ 
		    get
		    {
		        return this._employeur;
		    }
		    set
		    {
		        this._employeur = value;
		    }
		}
		
		private string _notes;
		public virtual string Notes 
		{ 
		    get
		    {
		        return this._notes;
		    }
		    set
		    {
		        this._notes = value;
		    }
		}
		
		private string _statut;
		public virtual string Statut 
		{ 
		    get
		    {
		        return this._statut;
		    }
		    set
		    {
		        this._statut = value;
		    }
		}
		
		private string _ajouter_Au;
		public virtual string Ajouter_au 
		{ 
		    get
		    {
		        return this._ajouter_Au;
		    }
		    set
		    {
		        this._ajouter_Au = value;
		    }
		}
		
		private string _ajouter_Par;
		public virtual string Ajouter_par 
		{ 
		    get
		    {
		        return this._ajouter_Par;
		    }
		    set
		    {
		        this._ajouter_Par = value;
		    }
		}
		
		private string _modifier_Au;
		public virtual string Modifier_au 
		{ 
		    get
		    {
		        return this._modifier_Au;
		    }
		    set
		    {
		        this._modifier_Au = value;
		    }
		}
		
		private string _modifier_Par;
		public virtual string Modifier_par 
		{ 
		    get
		    {
		        return this._modifier_Par;
		    }
		    set
		    {
		        this._modifier_Par = value;
		    }
		}
		
		private string _date_De_La_Dernière_Connexion;
		public virtual string Date_de_la_dernière_connexion 
		{ 
		    get
		    {
		        return this._date_De_La_Dernière_Connexion;
		    }
		    set
		    {
		        this._date_De_La_Dernière_Connexion = value;
		    }
		}
		
	}
}
