#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace HCP.Fr.SqlCe.DataAccess	
{
	public partial class Patients_tracking
	{
		private Guid _id;
		public virtual Guid Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int _sync_Row_Is_Tombstone;
		public virtual int Sync_row_is_tombstone 
		{ 
		    get
		    {
		        return this._sync_Row_Is_Tombstone;
		    }
		    set
		    {
		        this._sync_Row_Is_Tombstone = value;
		    }
		}
		
		private int _sync_Update_Peer_Key;
		public virtual int Sync_update_peer_key 
		{ 
		    get
		    {
		        return this._sync_Update_Peer_Key;
		    }
		    set
		    {
		        this._sync_Update_Peer_Key = value;
		    }
		}
		
		private long _sync_Update_Peer_Timestamp;
		public virtual long Sync_update_peer_timestamp 
		{ 
		    get
		    {
		        return this._sync_Update_Peer_Timestamp;
		    }
		    set
		    {
		        this._sync_Update_Peer_Timestamp = value;
		    }
		}
		
		private int _sync_Create_Peer_Key;
		public virtual int Sync_create_peer_key 
		{ 
		    get
		    {
		        return this._sync_Create_Peer_Key;
		    }
		    set
		    {
		        this._sync_Create_Peer_Key = value;
		    }
		}
		
		private long _sync_Create_Peer_Timestamp;
		public virtual long Sync_create_peer_timestamp 
		{ 
		    get
		    {
		        return this._sync_Create_Peer_Timestamp;
		    }
		    set
		    {
		        this._sync_Create_Peer_Timestamp = value;
		    }
		}
		
		private long _sync_Update_Bsn;
		public virtual long Sync_update_bsn 
		{ 
		    get
		    {
		        return this._sync_Update_Bsn;
		    }
		    set
		    {
		        this._sync_Update_Bsn = value;
		    }
		}
		
		private DateTime? _last_Change_Datetime;
		public virtual DateTime? Last_change_datetime 
		{ 
		    get
		    {
		        return this._last_Change_Datetime;
		    }
		    set
		    {
		        this._last_Change_Datetime = value;
		    }
		}
		
	}
}
