#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace HCP.Fr.SqlCe.DataAccess	
{
	public partial class Schema_info
	{
		private int _schema_Major_Version;
		public virtual int Schema_major_version 
		{ 
		    get
		    {
		        return this._schema_Major_Version;
		    }
		    set
		    {
		        this._schema_Major_Version = value;
		    }
		}
		
		private int _schema_Minor_Version;
		public virtual int Schema_minor_version 
		{ 
		    get
		    {
		        return this._schema_Minor_Version;
		    }
		    set
		    {
		        this._schema_Minor_Version = value;
		    }
		}
		
		private string _schema_Extended_Info;
		public virtual string Schema_extended_info 
		{ 
		    get
		    {
		        return this._schema_Extended_Info;
		    }
		    set
		    {
		        this._schema_Extended_Info = value;
		    }
		}
		
	}
}
