#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace HCP.Fr.SqlCe.DataAccess	
{
	public partial class Scope_info
	{
		private int _scope_Local_Id;
		public virtual int Scope_local_id 
		{ 
		    get
		    {
		        return this._scope_Local_Id;
		    }
		    set
		    {
		        this._scope_Local_Id = value;
		    }
		}
		
		private Guid _scope_Id;
		public virtual Guid Scope_id 
		{ 
		    get
		    {
		        return this._scope_Id;
		    }
		    set
		    {
		        this._scope_Id = value;
		    }
		}
		
		private string _sync_Scope_Name;
		public virtual string Sync_scope_name 
		{ 
		    get
		    {
		        return this._sync_Scope_Name;
		    }
		    set
		    {
		        this._sync_Scope_Name = value;
		    }
		}
		
		private byte[] _scope_Sync_Knowledge;
		public virtual byte[] Scope_sync_knowledge 
		{ 
		    get
		    {
		        return this._scope_Sync_Knowledge;
		    }
		    set
		    {
		        this._scope_Sync_Knowledge = value;
		    }
		}
		
		private byte[] _scope_Tombstone_Cleanup_Knowledge;
		public virtual byte[] Scope_tombstone_cleanup_knowledge 
		{ 
		    get
		    {
		        return this._scope_Tombstone_Cleanup_Knowledge;
		    }
		    set
		    {
		        this._scope_Tombstone_Cleanup_Knowledge = value;
		    }
		}
		
		private long? _scope_Timestamp;
		public virtual long? Scope_timestamp 
		{ 
		    get
		    {
		        return this._scope_Timestamp;
		    }
		    set
		    {
		        this._scope_Timestamp = value;
		    }
		}
		
		private long? _snapshot_Timestamp;
		public virtual long? Snapshot_timestamp 
		{ 
		    get
		    {
		        return this._snapshot_Timestamp;
		    }
		    set
		    {
		        this._snapshot_Timestamp = value;
		    }
		}
		
		private Guid? _scope_Config_Id;
		public virtual Guid? Scope_config_id 
		{ 
		    get
		    {
		        return this._scope_Config_Id;
		    }
		    set
		    {
		        this._scope_Config_Id = value;
		    }
		}
		
		private string _scope_User_Comment;
		public virtual string Scope_user_comment 
		{ 
		    get
		    {
		        return this._scope_User_Comment;
		    }
		    set
		    {
		        this._scope_User_Comment = value;
		    }
		}
		
		private long _scope_Tomb_Mark;
		public virtual long Scope_tomb_mark 
		{ 
		    get
		    {
		        return this._scope_Tomb_Mark;
		    }
		    set
		    {
		        this._scope_Tomb_Mark = value;
		    }
		}
		
	}
}
