#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace HCP.Fr.SqlCe.DataAccess	
{
	public partial class Scope_config
	{
		private Guid _config_Id;
		public virtual Guid Config_id 
		{ 
		    get
		    {
		        return this._config_Id;
		    }
		    set
		    {
		        this._config_Id = value;
		    }
		}
		
		private string _config_Data;
		public virtual string Config_data 
		{ 
		    get
		    {
		        return this._config_Data;
		    }
		    set
		    {
		        this._config_Data = value;
		    }
		}
		
	}
}
