//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP.Fr.DS.Logs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLogs
    {
        public int Id { get; set; }
        public string application { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public string Nom_de_fichier { get; set; }
        public Nullable<int> Numéro_de_ligne { get; set; }
        public string nom_de_la_méthode { get; set; }
        public string trace_de_la_pile { get; set; }
        public Nullable<int> HResult { get; set; }
        public string HelpURL { get; set; }
        public string ajouter_au { get; set; }
        public string ajouter_par { get; set; }
        public string modifier_au { get; set; }
        public string modifier_par { get; set; }
        public string date_de_la_dernière_connexion { get; set; }
    }
}
