//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCP.Fr.DS.SqlCe.ABIBOUPC
{

    public partial class Patients : XPLiteObject
    {
        Guid fId;
        [Key(true)]
        public Guid Id
        {
            get { return fId; }
            set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
        }
        string fssn_ou_identité;
        public string ssn_ou_identité
        {
            get { return fssn_ou_identité; }
            set { SetPropertyValue<string>(nameof(ssn_ou_identité), ref fssn_ou_identité, value); }
        }
        string fnumero_carte_identité;
        [Size(50)]
        public string numero_carte_identité
        {
            get { return fnumero_carte_identité; }
            set { SetPropertyValue<string>(nameof(numero_carte_identité), ref fnumero_carte_identité, value); }
        }
        string fIdentité_expiration;
        [Size(50)]
        public string Identité_expiration
        {
            get { return fIdentité_expiration; }
            set { SetPropertyValue<string>(nameof(Identité_expiration), ref fIdentité_expiration, value); }
        }
        string fIdentité_date_de_publication;
        [Size(50)]
        public string Identité_date_de_publication
        {
            get { return fIdentité_date_de_publication; }
            set { SetPropertyValue<string>(nameof(Identité_date_de_publication), ref fIdentité_date_de_publication, value); }
        }
        string fadresse_carte_identité;
        public string adresse_carte_identité
        {
            get { return fadresse_carte_identité; }
            set { SetPropertyValue<string>(nameof(adresse_carte_identité), ref fadresse_carte_identité, value); }
        }
        string fnom;
        public string nom
        {
            get { return fnom; }
            set { SetPropertyValue<string>(nameof(nom), ref fnom, value); }
        }
        string fprénom;
        public string prénom
        {
            get { return fprénom; }
            set { SetPropertyValue<string>(nameof(prénom), ref fprénom, value); }
        }
        string fdeuxième_nom;
        public string deuxième_nom
        {
            get { return fdeuxième_nom; }
            set { SetPropertyValue<string>(nameof(deuxième_nom), ref fdeuxième_nom, value); }
        }
        string fdate_naissance;
        public string date_naissance
        {
            get { return fdate_naissance; }
            set { SetPropertyValue<string>(nameof(date_naissance), ref fdate_naissance, value); }
        }
        string fraison_de_la_visite;
        [Size(SizeAttribute.Unlimited)]
        public string raison_de_la_visite
        {
            get { return fraison_de_la_visite; }
            set { SetPropertyValue<string>(nameof(raison_de_la_visite), ref fraison_de_la_visite, value); }
        }
        string ftaille;
        [Size(20)]
        public string taille
        {
            get { return ftaille; }
            set { SetPropertyValue<string>(nameof(taille), ref ftaille, value); }
        }
        string fyeux;
        [Size(50)]
        public string yeux
        {
            get { return fyeux; }
            set { SetPropertyValue<string>(nameof(yeux), ref fyeux, value); }
        }
        string fcheveux;
        [Size(50)]
        public string cheveux
        {
            get { return fcheveux; }
            set { SetPropertyValue<string>(nameof(cheveux), ref fcheveux, value); }
        }
        string fadresse;
        [Size(300)]
        public string adresse
        {
            get { return fadresse; }
            set { SetPropertyValue<string>(nameof(adresse), ref fadresse, value); }
        }
        string fappartement;
        [Size(20)]
        public string appartement
        {
            get { return fappartement; }
            set { SetPropertyValue<string>(nameof(appartement), ref fappartement, value); }
        }
        string fville;
        [Size(300)]
        public string ville
        {
            get { return fville; }
            set { SetPropertyValue<string>(nameof(ville), ref fville, value); }
        }
        string fétat_ou_région;
        [Size(300)]
        public string état_ou_région
        {
            get { return fétat_ou_région; }
            set { SetPropertyValue<string>(nameof(état_ou_région), ref fétat_ou_région, value); }
        }
        string fPays;
        [Size(300)]
        public string Pays
        {
            get { return fPays; }
            set { SetPropertyValue<string>(nameof(Pays), ref fPays, value); }
        }
        string fboite_postale;
        [Size(50)]
        public string boite_postale
        {
            get { return fboite_postale; }
            set { SetPropertyValue<string>(nameof(boite_postale), ref fboite_postale, value); }
        }
        string fgenre;
        [Size(50)]
        public string genre
        {
            get { return fgenre; }
            set { SetPropertyValue<string>(nameof(genre), ref fgenre, value); }
        }
        string fnaissance;
        [Size(20)]
        public string naissance
        {
            get { return fnaissance; }
            set { SetPropertyValue<string>(nameof(naissance), ref fnaissance, value); }
        }
        string flieux_naissance;
        [Size(50)]
        public string lieux_naissance
        {
            get { return flieux_naissance; }
            set { SetPropertyValue<string>(nameof(lieux_naissance), ref flieux_naissance, value); }
        }
        string ftéléphone;
        [Size(20)]
        public string téléphone
        {
            get { return ftéléphone; }
            set { SetPropertyValue<string>(nameof(téléphone), ref ftéléphone, value); }
        }
        string ffax;
        [Size(20)]
        public string fax
        {
            get { return ffax; }
            set { SetPropertyValue<string>(nameof(fax), ref ffax, value); }
        }
        string femail;
        [Size(200)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string ftwitter;
        [Size(200)]
        public string twitter
        {
            get { return ftwitter; }
            set { SetPropertyValue<string>(nameof(twitter), ref ftwitter, value); }
        }
        string fwhatsapp;
        [Size(200)]
        public string whatsapp
        {
            get { return fwhatsapp; }
            set { SetPropertyValue<string>(nameof(whatsapp), ref fwhatsapp, value); }
        }
        string flinkedin;
        [Size(200)]
        public string linkedin
        {
            get { return flinkedin; }
            set { SetPropertyValue<string>(nameof(linkedin), ref flinkedin, value); }
        }
        string femployeur;
        [Size(200)]
        public string employeur
        {
            get { return femployeur; }
            set { SetPropertyValue<string>(nameof(employeur), ref femployeur, value); }
        }
        string fnotes;
        [Size(SizeAttribute.Unlimited)]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>(nameof(notes), ref fnotes, value); }
        }
        string fstatut;
        public string statut
        {
            get { return fstatut; }
            set { SetPropertyValue<string>(nameof(statut), ref fstatut, value); }
        }
        string fajouter_au;
        public string ajouter_au
        {
            get { return fajouter_au; }
            set { SetPropertyValue<string>(nameof(ajouter_au), ref fajouter_au, value); }
        }
        string fajouter_par;
        [Size(200)]
        public string ajouter_par
        {
            get { return fajouter_par; }
            set { SetPropertyValue<string>(nameof(ajouter_par), ref fajouter_par, value); }
        }
        string fmodifier_au;
        public string modifier_au
        {
            get { return fmodifier_au; }
            set { SetPropertyValue<string>(nameof(modifier_au), ref fmodifier_au, value); }
        }
        string fmodifier_par;
        [Size(200)]
        public string modifier_par
        {
            get { return fmodifier_par; }
            set { SetPropertyValue<string>(nameof(modifier_par), ref fmodifier_par, value); }
        }
        string fdate_de_la_dernière_connexion;
        [Size(200)]
        public string date_de_la_dernière_connexion
        {
            get { return fdate_de_la_dernière_connexion; }
            set { SetPropertyValue<string>(nameof(date_de_la_dernière_connexion), ref fdate_de_la_dernière_connexion, value); }
        }
        long fP__sysChangeTxBsn;
        [Indexed(Name = @"sysChangeTxBsn_idx")]
        [Persistent(@"__sysChangeTxBsn")]
        public long P__sysChangeTxBsn
        {
            get { return fP__sysChangeTxBsn; }
            set { SetPropertyValue<long>(nameof(P__sysChangeTxBsn), ref fP__sysChangeTxBsn, value); }
        }
        long fP__sysInsertTxBsn;
        [Persistent(@"__sysInsertTxBsn")]
        public long P__sysInsertTxBsn
        {
            get { return fP__sysInsertTxBsn; }
            set { SetPropertyValue<long>(nameof(P__sysInsertTxBsn), ref fP__sysInsertTxBsn, value); }
        }
        Guid fP__sysTrackingContext;
        [Persistent(@"__sysTrackingContext")]
        public Guid P__sysTrackingContext
        {
            get { return fP__sysTrackingContext; }
            set { SetPropertyValue<Guid>(nameof(P__sysTrackingContext), ref fP__sysTrackingContext, value); }
        }
    }

}
