//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCP.Fr.DS.SqlCe.ABIBOUPC
{

    public partial class Patients_tracking : XPLiteObject
    {
        Guid fId;
        [Key(true)]
        public Guid Id
        {
            get { return fId; }
            set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
        }
        int fsync_row_is_tombstone;
        public int sync_row_is_tombstone
        {
            get { return fsync_row_is_tombstone; }
            set { SetPropertyValue<int>(nameof(sync_row_is_tombstone), ref fsync_row_is_tombstone, value); }
        }
        int fsync_update_peer_key;
        public int sync_update_peer_key
        {
            get { return fsync_update_peer_key; }
            set { SetPropertyValue<int>(nameof(sync_update_peer_key), ref fsync_update_peer_key, value); }
        }
        long fsync_update_peer_timestamp;
        public long sync_update_peer_timestamp
        {
            get { return fsync_update_peer_timestamp; }
            set { SetPropertyValue<long>(nameof(sync_update_peer_timestamp), ref fsync_update_peer_timestamp, value); }
        }
        int fsync_create_peer_key;
        public int sync_create_peer_key
        {
            get { return fsync_create_peer_key; }
            set { SetPropertyValue<int>(nameof(sync_create_peer_key), ref fsync_create_peer_key, value); }
        }
        long fsync_create_peer_timestamp;
        public long sync_create_peer_timestamp
        {
            get { return fsync_create_peer_timestamp; }
            set { SetPropertyValue<long>(nameof(sync_create_peer_timestamp), ref fsync_create_peer_timestamp, value); }
        }
        long fsync_update_bsn;
        [Indexed(Name = @"sysChangeTxBsn_idx")]
        [ColumnDbDefaultValue("0")]
        public long sync_update_bsn
        {
            get { return fsync_update_bsn; }
            set { SetPropertyValue<long>(nameof(sync_update_bsn), ref fsync_update_bsn, value); }
        }
        DateTime flast_change_datetime;
        [ColumnDbDefaultValue("GETDATE()")]
        public DateTime last_change_datetime
        {
            get { return flast_change_datetime; }
            set { SetPropertyValue<DateTime>(nameof(last_change_datetime), ref flast_change_datetime, value); }
        }
    }

}
