//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCP.Fr.DS.SqlCe.ABIBOUPC
{

    public partial class schema_info : XPLiteObject
    {
        string fschema_extended_info;
        public string schema_extended_info
        {
            get { return fschema_extended_info; }
            set { SetPropertyValue<string>(nameof(schema_extended_info), ref fschema_extended_info, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("schema_major_version")]
            public int schema_major_version { get; set; }
            [Persistent("schema_minor_version")]
            public int schema_minor_version { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
