//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCP.Fr.DS.SqlCe.ABIBOUPC
{

    public partial class scope_info : XPLiteObject
    {
        int fscope_local_id;
        public int scope_local_id
        {
            get { return fscope_local_id; }
            set { SetPropertyValue<int>(nameof(scope_local_id), ref fscope_local_id, value); }
        }
        Guid fscope_id;
        [ColumnDbDefaultValue("NEWID()")]
        public Guid scope_id
        {
            get { return fscope_id; }
            set { SetPropertyValue<Guid>(nameof(scope_id), ref fscope_id, value); }
        }
        string fsync_scope_name;
        [Key]
        public string sync_scope_name
        {
            get { return fsync_scope_name; }
            set { SetPropertyValue<string>(nameof(sync_scope_name), ref fsync_scope_name, value); }
        }
        byte[] fscope_sync_knowledge;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] scope_sync_knowledge
        {
            get { return fscope_sync_knowledge; }
            set { SetPropertyValue<byte[]>(nameof(scope_sync_knowledge), ref fscope_sync_knowledge, value); }
        }
        byte[] fscope_tombstone_cleanup_knowledge;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] scope_tombstone_cleanup_knowledge
        {
            get { return fscope_tombstone_cleanup_knowledge; }
            set { SetPropertyValue<byte[]>(nameof(scope_tombstone_cleanup_knowledge), ref fscope_tombstone_cleanup_knowledge, value); }
        }
        long fscope_timestamp;
        public long scope_timestamp
        {
            get { return fscope_timestamp; }
            set { SetPropertyValue<long>(nameof(scope_timestamp), ref fscope_timestamp, value); }
        }
        long fsnapshot_timestamp;
        public long snapshot_timestamp
        {
            get { return fsnapshot_timestamp; }
            set { SetPropertyValue<long>(nameof(snapshot_timestamp), ref fsnapshot_timestamp, value); }
        }
        Guid fscope_config_id;
        public Guid scope_config_id
        {
            get { return fscope_config_id; }
            set { SetPropertyValue<Guid>(nameof(scope_config_id), ref fscope_config_id, value); }
        }
        string fscope_user_comment;
        [Size(SizeAttribute.Unlimited)]
        public string scope_user_comment
        {
            get { return fscope_user_comment; }
            set { SetPropertyValue<string>(nameof(scope_user_comment), ref fscope_user_comment, value); }
        }
        long fscope_tomb_mark;
        [ColumnDbDefaultValue("0")]
        public long scope_tomb_mark
        {
            get { return fscope_tomb_mark; }
            set { SetPropertyValue<long>(nameof(scope_tomb_mark), ref fscope_tomb_mark, value); }
        }
    }

}
