//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace HCP.Fr.DS.SqlCe.ABIBOUPC
{

    public partial class scope_config : XPLiteObject
    {
        Guid fconfig_id;
        [Key(true)]
        public Guid config_id
        {
            get { return fconfig_id; }
            set { SetPropertyValue<Guid>(nameof(config_id), ref fconfig_id, value); }
        }
        string fconfig_data;
        [Size(SizeAttribute.Unlimited)]
        public string config_data
        {
            get { return fconfig_data; }
            set { SetPropertyValue<string>(nameof(config_data), ref fconfig_data, value); }
        }
    }

}
