//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP.Fr.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nurses
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Spécialité { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string deuxième_nom { get; set; }
        public string date_naissance { get; set; }
        public string adresse { get; set; }
        public string appartement { get; set; }
        public string ville { get; set; }
        public string état_ou_région { get; set; }
        public string Pays { get; set; }
        public string boite_postale { get; set; }
        public string téléphone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string twitter { get; set; }
        public string whatsapp { get; set; }
        public string linkedin { get; set; }
        public string employeur { get; set; }
        public string notes { get; set; }
        public string ajouter_au { get; set; }
        public string ajouter_par { get; set; }
        public string modifier_au { get; set; }
        public string modifier_par { get; set; }
        public string date_de_la_dernière_connexion { get; set; }
    
        public virtual Specialities Specialities { get; set; }
    }
}
