//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP.Fr.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientIdentities
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public byte[] Fichier { get; set; }
        public System.Guid PatId { get; set; }
        public string Taille { get; set; }
        public string longueur { get; set; }
        public string largeur { get; set; }
        public string ajouter_au { get; set; }
        public string ajouter_par { get; set; }
        public string modifier_au { get; set; }
        public string modifier_par { get; set; }
        public string Chemin_Du_Fichier { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
