//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP.Fr.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Addresses
    {
        public int PadId { get; set; }
        public System.Guid Id { get; set; }
        public string adresse { get; set; }
        public string appartement { get; set; }
        public string ville { get; set; }
        public string état_ou_région { get; set; }
        public string Pays { get; set; }
        public string boite_postale { get; set; }
        public string téléphone { get; set; }
        public string Notes { get; set; }
        public string ajouter_au { get; set; }
        public string ajouter_par { get; set; }
        public string modifier_au { get; set; }
        public string modifier_par { get; set; }
    }
}
