//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP.Fr.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specialities()
        {
            this.Doctors = new HashSet<Doctors>();
            this.Nurses = new HashSet<Nurses>();
            this.Patients_Doctors_Relations = new HashSet<Patients_Doctors_Relations>();
            this.Patients_Nurses_Relations = new HashSet<Patients_Nurses_Relations>();
            this.Sub_Specialties = new HashSet<Sub_Specialties>();
        }
    
        public int Id { get; set; }
        public string Spécialité { get; set; }
        public string Description { get; set; }
        public bool Statut { get; set; }
        public string AjouterAu { get; set; }
        public string AjouterPar { get; set; }
        public string ModifierAu { get; set; }
        public string ModifierPar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctors> Doctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nurses> Nurses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patients_Doctors_Relations> Patients_Doctors_Relations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patients_Nurses_Relations> Patients_Nurses_Relations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Specialties> Sub_Specialties { get; set; }
    }
}
