//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP.Fr.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Specialties
    {
        public int Id { get; set; }
        public string Spécialité { get; set; }
        public string Sous_Spécialité { get; set; }
        public string Description { get; set; }
        public bool Statut { get; set; }
        public string AjouterAu { get; set; }
        public string AjouterPar { get; set; }
        public string ModifierAu { get; set; }
        public string ModifierPar { get; set; }
    
        public virtual Specialities Specialities { get; set; }
    }
}
