//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP.Fr.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAccessLogs
    {
        public int SysId { get; set; }
        public System.Guid Id { get; set; }
        public string ordinateur { get; set; }
        public string IP { get; set; }
        public string début { get; set; }
        public string fin { get; set; }
        public string ajouter_au { get; set; }
        public string ajouter_par { get; set; }
        public string modifier_au { get; set; }
        public string modifier_par { get; set; }
        public string date_de_la_dernière_connexion { get; set; }
    }
}
