//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP.Fr.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public System.Guid Id { get; set; }
        public string email { get; set; }
        public byte[] password { get; set; }
        public string nom_role { get; set; }
        public string Statut { get; set; }
        public string notes { get; set; }
        public string ajouter_au { get; set; }
        public string ajouter_par { get; set; }
        public string modifier_au { get; set; }
        public string modifier_par { get; set; }
        public string date_de_la_dernière_connexion { get; set; }
        public string Nom { get; set; }
        public string prénom { get; set; }
        public string deuxième_nom { get; set; }
    }
}
