// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NorthwindEndPointApi.Entities;

[Keyless]
public partial class UserData
{
    public int Id { get; set; }

    [Required]
    [StringLength(4000)]
    public string email { get; set; }

    [Required]
    [StringLength(100)]
    public string password { get; set; }

    public DateTime created { get; set; }

    public DateTime? updated { get; set; }
}