// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NorthwindEndPointApi.Entities;

public partial class users
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string name { get; set; }

    public int age { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string location { get; set; }

    [Column(TypeName = "date")]
    public DateTime createdat { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string createdby { get; set; }

    [Column(TypeName = "date")]
    public DateTime? updatedat { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string updatedby { get; set; }
}